<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Humanizer.Core.fa" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />

	</ItemGroup>

</Project>

