<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Settings.Configuration" />
		<PackageReference Include="Serilog.Sinks.Async" />
		<PackageReference Include="Serilog.Sinks.MSSqlServer" />
		<PackageReference Include="Serilog.UI" />
		<PackageReference Include="Serilog.UI.MsSqlServerProvider" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Mkx.Templates.Sdk.Server.Application\Mkx.Templates.Sdk.Server.Application.csproj" />
		<ProjectReference Include="..\..\Shared\Mkx.Templates.Sdk.Shared\Mkx.Templates.Sdk.Shared.csproj" />
	</ItemGroup>

</Project>

